# Generated by Django 5.2.4 on 2025-07-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='complement',
            field=models.CharField(blank=True, help_text='Additional address information (apt, suite, etc)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='country',
            field=models.CharField(blank=True, help_text='Country name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='state',
            field=models.CharField(blank=True, help_text='State/province name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='street_name',
            field=models.CharField(blank=True, help_text='Street name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='street_number',
            field=models.CharField(blank=True, help_text='Building/location number', max_length=20, null=True),
        ),
    ]
