# Generated by Django 5.2.4 on 2025-07-07 00:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gym_city_gym_complement_gym_country_gym_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_due_date',
            field=models.DateField(default=core.models.Subscription.get_first_day_next_month),
        ),
    ]
